### ISSUE TITLE
"TADA68 Keyboard Fireware Editor" websied  cannot be accessed

### ISSUE THREAD

**Issue by tempestLXC** [ravicious/TADA68#2]
websied  cannot be accessed

**Comment by ravicious** [comment]
That's unfortunate. ☹️ Did you try contacting the support? I'd consider that or checking if people on [/r/MechanicalKeyboards](https://www.reddit.com/r/MechanicalKeyboards) are already aware of any workarounds.

**Comment by davidgibsonp** [comment]
Experiencing the same issue... Contacted Originative and the sent me to this repo

**Comment by ravicious** [comment]
Looks like the editor is back up online. I'm not sure why they sent you over to my repo since it won't solve your problems if the editor is down. 😅

**Comment by davidgibsonp** [comment]
Guess my email work lol
