### ISSUE TITLE
Firmware Editor is down

### ISSUE THREAD

**Issue by nepthar** [ravicious/TADA68#3]
http://123.57.250.164:3000/tada68 no longer works. The larger issue is that one has to go to a totally unknown website and run untrusted code. Can this editor be made part of this repo somehow?

**Comment by ravicious** [comment]
Just FYI, this repo isn't an official repo in any way and I'm not associated with people who made the keyboard or the editor.

However, back in the day I was worried that this would happen. I saved the page source then, check out the attachment. The editor doesn't seem to work just if I open the saved page, but if you manage to get it to work, make a PR and I'll be happy to merge it.

[tada68-editor.zip](https://github.com/ravicious/TADA68/files/3687281/tada68-editor.zip)

**Comment by nepthar** [comment]
Thanks, I'll take a look at it.

**Comment by nepthar** [comment]
I played around with it for a bit and got the SWF file to load directly (using an object tag) but I think I'm stuck there. I'm not particularly knowledgeable in this area, but I'll leave some notes.

- The swf file seems to want at least two "flashvars" set: href=window.location.href and kbtype=kb68.
- I can't be sure if the SWFObject JS library is working correctly
- While I think the swf file is running, I think it halts on some error I can't see with regular chrome developer tools.

**Comment by przemyslawhaptas** [comment]
hey @nepthar, ~I haven't tried it myself but~ this site seems to have everything you need: https://config.qmk.fm/#/tada68/LAYOUT_ansi

**Comment by nepthar** [comment]
Oops, forgot to close this issue. Thanks!
